### ISSUE TITLE
functions inside module not exported properly

### ISSUE THREAD

**Issue by berceanu** [malmaud/Autoreload.jl#17]
I created a file called `MyModule.jl` with the following content (copied from the Julia manual)
```
module MyModule

export x, y

x() = "x"
y() = "y"
p() = "p"

end
```
from the `REPL`, I can do
```
using MyModule
x()
```
--> "x"

Now I would like to use the `Autoreload` package. So in the `REPL` I do
```
using Autoreload
arequire("MyModule")
x()
```
--> ERROR: x not defined

I see that `MyModule.x()` seems to work but this means the exports are completely ignored and furthermore results in cumbersome code, as one has to put the module name in front of everything. Is there a workaround?

ps: sorry about the double posting (https://groups.google.com/forum/#!topic/julia-users/29FO_YsJhM0) but I got no reply on the mailing list.

**Comment by davidanthoff** [comment]
Maybe there should be a ``ausing()`` function for this case?

**Comment by cstjean** [comment]
I use 
```julia
arequire("Foo")
using Foo```
and it generally works.

**Comment by malmaud** [comment]
There are two orthogonal issues here: `arequire` re-evals the content of a Julia source file, and `using` exports the symbols marked with `export` from a module. There's in general no relationship between a source file and a module. 

But it would be nice to have a convenience function for this common case.

**Comment by malmaud** [comment]
There's now an `@aimport` and `@ausing` macro that simulates `import` and `using`. eg

``` julia
@ausing Foo
```

**Comment by cstjean** [comment]
Nice! If I have "module A depends on B", I still need `arequire(..., depends_on=)`, right?

**Comment by malmaud** [comment]
Ya, assuming that dependence isn't automatically discovered through `include` directives. Suggestions welcome for syntactic sugar for that case.

**Comment by cstjean** [comment]
Not a great one, but maybe `@ausing A <: B` ?

**Comment by malmaud** [comment]
Not a bad idea. I implemented that on the `sugar` branch.

**Comment by cstjean** [comment]
@malmaud I don't think I can comment directly on `sugar` since it's not a PR, but on [this line](https://github.com/malmaud/Autoreload.jl/compare/sugar#diff-0033f9de61e25a98b730785191eb2c68L14) it should be `macro using` - you're defining `import` twice.

**Comment by malmaud** [comment]
Oh woops
