### ISSUE TITLE
Access denied on Win7x64

### ISSUE THREAD

**Issue by BenStrowbridge** [malmaud/Autoreload.jl#18]
I have a dual boot system with Yosemite and Win7x64. Autoreload works fine on the Mac OS but does not appear to release the file write permission on Windows. I get an "Access Denied" error when I try to revise the source code in the editor. That error that goes away when I close the Julia terminal window. I am using SublimeText3 to edit the source file under both systems. The "arequire" function works under Windows to load in the module so it seems like there is just an issue related to file permissions.

**Comment by davidanthoff** [comment]
I have the same problem, and essentially it makes this package unusable...

**Comment by malmaud** [comment]
I'll look into it.

**Comment by malmaud** [comment]
I don't have a Windows machine to test on, but I think I may have fixed this. Can you check if the current master branch works now?

**Comment by davidanthoff** [comment]
I can't test right now, package doesn't work on julia 0.3.6 (see #20 and #21).

**Comment by davidanthoff** [comment]
With my PR that fixes #21 this now all works.

**Comment by malmaud** [comment]
Closing since it seems like it works now. Do let me know if otherwise, though.
