### ISSUE TITLE
Parametric types break autoreload

### ISSUE THREAD

**Issue by cstjean** [malmaud/Autoreload.jl#23]
This may be a known issue but on Julia 0.3, going from:
```
module TestM

immutable Foo{T}
    x::T
end

end
 ```
to:
```
module TestM
# Random comment
immutable Foo{T}
    x::T
end

end 
```
yields `invalid redefinition of constant Foo` on autoreload. This is only true with parametric types, so it may be an issue with Julia itself.

**Comment by malmaud** [comment]
Ya, in base Julia you can't redefine parametric types.

**Comment by malmaud** [comment]
It might not be hopeless though - we can just strip out the type definition from the AST before passing it to Julia for eval.

**Comment by cstjean** [comment]
That would be appreciated. Right now, I have to isolate my parametric
datastructures in non-autoreloaded mini-modules.

**Comment by malmaud** [comment]
Actually, let's close in favor of https://github.com/malmaud/Autoreload.jl/issues/23.
