### ISSUE TITLE
Work with julia 0.4?

### ISSUE THREAD

**Issue by robertfeldt** [malmaud/Autoreload.jl#25]
Have had problems using this package with julia 0.4. Any plans on updating it?

**Comment by malmaud** [comment]
Yes, I would like to get it working again. Part of the lack of activity is because I've started using Atom.jl for my own work, which mitigates some of the workflow problems this package was meant to help.

**Comment by robertfeldt** [comment]
This type of functionality is still much needed in for example automated testing tools where you want to reload and rerun code based on recent changes. If I can help in some way to update this package please indicate what I can do. It would be great to get it up and running again. :)

**Comment by malmaud** [comment]
Well, I'd welcome pull requests. Besides for that, I'll have to investigate first to figure out what needs to be done to get things with modern Julia. 

I am a little curious though if it might be easiest for you to set up your automated testing in such a way that a new Julia process is launched every time a new batch of tests is to be run.

**Comment by robertfeldt** [comment]
Well, I'm doing continuous testing here in minimal increments so performance is critical but you are right in the sense that I'm not sure how the new pre-compilation of Julia 0.4 will affect things so other method might be called for.

If/when you have some list of things that needs to be fixed I'll try to help out and do PR's as appropriate. Cheers.

**Comment by cstjean** [comment]
@robertfeldt [This one-line change](https://github.com/hayd/Autoreload.jl/commit/622c07a34e2738dc80d7e0893dd917805bda99fa#diff-d3b25e53029d87d047f0f7e2e3c6e677L53) is all you need to get it working on 0.4 until that pull request gets merged. You'll still get deprecation warnings, but those can be ignored.

**Comment by malmaud** [comment]
master branch seems to be working fine on 0.4 now.
