### ISSUE TITLE
Depends_on does not work with chained dependencies

### ISSUE THREAD

**Issue by cstjean** [malmaud/Autoreload.jl#27]
`depends_on` does not work at all for me, in fact, given

```julia
arequire("A")
arequire("B", depends_on=["A"])
```
The second line will disable any reloading for "A" because it calls `arequire("A"; command=:on_depends)`, which sets `files[".../A.jl"].should_reload` to `false` [here](https://github.com/malmaud/Autoreload.jl/blob/master/src/Autoreload.jl#L59) and that is a [necessary condition](https://github.com/malmaud/Autoreload.jl/blob/master/src/Autoreload.jl#L181) for reloading.

In any case, I'm happy to rework the logic and fix it myself, I just want to make sure that I'm clear on the desired interface. If I have modules A, B, and C, B depending on A and C depending on B, I assume that I should write 

```julia
arequire("A")
arequire("B", depends_on=["A"])
arequire("C", depends_on=["B"])
```

and  modifying A will trigger updates to A, B and C. Is that correct?

**Comment by phobon** [comment]
I came here to post this same issue. I get the behavior I want regarding dependencies if I hard code `should_reload` to always be `true`. It's not clear to me why it should ever be `false`.

**Comment by malmaud** [comment]
I'm about to modernize this package to work with Julia .4, and in the process will fix this.

**Comment by malmaud** [comment]
I am sure at some point I had a reason for the `should_reload` mechanic, but whatever it was, it does seem erroneous now.

**Comment by malmaud** [comment]
Ah, I remember now. The situation `should_reload=false` is useful in is if you want a.jl to reload whenever b.jl changes, but b.jl is not a stand-alone file that could be included on its own (for example, it relies on some constants defined in `a`). It's a common situation in packages. 

So if you both want `a.jl` to reload when `b.jl` changes, but also `b.jl` to reload whenever `b.jl` changes, the proper code is

```
arequire("b")
arequire("a", depens_on=["b"])
```

It was a bug that this wasn't working before, fixed now.
